# Generated by Django 4.2.16 on 2024-10-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
