# Generated by Django 4.2.16 on 2024-10-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0010_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='ticker',
            field=models.CharField(max_length=15),
        ),
    ]
