# Generated by Django 4.2.16 on 2024-10-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0018_watchlist_added_at_alter_watchlist_ticker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
